### ISSUE TITLE
fail to get MapSet docs

### ISSUE THREAD

**Issue by slashmili** [msaraiva/elixir_sense#21]
It's been reported that MapSet doc doesn't work as expected, I added a test case and got error:

https://github.com/slashmili/alchemist.vim/issues/123
```
    test "retrieve MapSet documentation" do
      buffer = """
      defmodule MyModule do
        MapSet
      end
      """

      %{
        subject: subject,
        actual_subject: actual_subject,
        docs: %{docs: docs}
      } = ElixirSense.docs(buffer, 2, 3)
  end
```

```
  1) test docs retrieve MapSet documentation (ElixirSense.DocsTest)
     test/elixir_sense/docs_test.exs:7
     ** (FunctionClauseError) no function clause matching in ElixirSense.Core.Introspection.extract_spec_ast_parts/1

     The following arguments were given to ElixirSense.Core.Introspection.extract_spec_ast_parts/1:

         # 1
         {:t, [], [{:value, 41, nil}]}

     Attempted function clauses (showing 2 out of 2):

         defp extract_spec_ast_parts({:when, _, [{:::, _, [name_part, return_part]}, when_part]})
         defp extract_spec_ast_parts({:::, _, [name_part, return_part]})

     code: } = ElixirSense.docs(buffer, 2, 3)
     stacktrace:
       (elixir_sense) lib/elixir_sense/core/introspection.ex:227: ElixirSense.Core.Introspection.extract_spec_ast_parts/1
       (elixir_sense) lib/elixir_sense/core/introspection.ex:171: ElixirSense.Core.Introspection.format_spec_ast/1
       (elixir_sense) lib/elixir_sense/core/introspection.ex:153: ElixirSense.Core.Introspection.format_type/1
       (elixir_sense) lib/elixir_sense/core/introspection.ex:133: anonymous fn/2 in ElixirSense.Core.Introspection.get_types_with_docs/1
       (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
       (elixir_sense) lib/elixir_sense/core/introspection.ex:80: ElixirSense.Core.Introspection.get_types_md/1
       (elixir_sense) lib/elixir_sense/core/introspection.ex:30: ElixirSense.Core.Introspection.get_all_docs/1
       (elixir_sense) lib/elixir_sense/providers/docs.ex:13: ElixirSense.Providers.Docs.all/4
       (elixir_sense) lib/elixir_sense.ex:49: ElixirSense.docs/3
       test/elixir_sense/docs_test.exs:18: (test)
```

**Comment by slashmili** [comment]
It's been fixed in the new version. Thanks!
