### ISSUE TITLE
Crash in docs/3 when used from elixir-ls

### ISSUE THREAD

**Issue by lukaszsamson** [msaraiva/elixir_sense#32]
Elixir version:
Erlang/OTP 21 [erts-10.0.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]
Elixir 1.7.1 (compiled with Erlang/OTP 21)
elixir_sense: github master

```
    ** (FunctionClauseError) no function clause matching in ElixirSense.Core.Introspection.extract_spec_ast_parts/1
        (elixir_sense) lib/elixir_sense/core/introspection.ex:282: ElixirSense.Core.Introspection.extract_spec_ast_parts({:t, [], [{:value, 41, nil}]})
        (elixir_sense) lib/elixir_sense/core/introspection.ex:226: ElixirSense.Core.Introspection.format_spec_ast/1
        (elixir_sense) lib/elixir_sense/core/introspection.ex:208: ElixirSense.Core.Introspection.format_type/1
        (elixir_sense) lib/elixir_sense/core/introspection.ex:181: anonymous fn/2 in ElixirSense.Core.Introspection.get_types_with_docs/1
        (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
        (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
        (elixir_sense) lib/elixir_sense/core/introspection.ex:128: ElixirSense.Core.Introspection.get_types_md/1
        (elixir_sense) lib/elixir_sense/core/introspection.ex:78: ElixirSense.Core.Introspection.get_all_docs/1
        (elixir_sense) lib/elixir_sense/providers/docs.ex:13: ElixirSense.Providers.Docs.all/4
        (elixir_sense) lib/elixir_sense.ex:50: ElixirSense.docs/3
```

**Comment by lukaszsamson** [comment]
Some more not matched values:
{:key, [], []}
{:dist_handle, [], []}
{:prepared_code, [], []}

**Comment by msaraiva** [comment]
Fixed! Private/internal types, i.e., @opaque and @typep are ignored now.

Thanks for reporting this issue.
